apiVersion: apps/v1
kind: Deployment
metadata:
  name: srv
spec:
  template:
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: srv
          imagePullPolicy: IfNotPresent
