# Use :nonroot base image for all containers
# defaultBaseImage: gcr.io/distroless/static:nonroot
# Use: busybox to debug container
# baseImageOverrides:
#   github.com/xmlking/micro-starter-kit/srv/account: busybox
#   github.com/xmlking/micro-starter-kit/srv/emailer: busybox

# defaultBaseImage: gcr.io/distroless/base
