environment: production
name: go.micro.srv.account
version: 0.1.0
log:
  level: info
  format: text
database:
  dialect: postgres
  host: localhost
  port: 5432
  Username: postgres
  Password: postgres321
  database: postgres
  logging: true
observability:
  metrics:
    address: localhost:8125
    flushInterval: 1000000000
  tracing:
    address: jaeger:6831
    flushInterval: 5000000000