environment: production
name: account-api
version: v0.1.0
log:
  level: info
  format: json
observability:
  metrics:
    address: prometheus:8125
    flushInterval: 1000000000
  tracing:
    address: jaeger:6831
    flushInterval: 5000000000
account-srv:
  endpoint: account-srv
  version: v0.1.0
