namespace: default
namePrefix: dev-

commonLabels:
  environment: development
commonAnnotations:
  note: Hello, I am dev!

bases:
  - ../../bases

configMapGenerator:
  - behavior: merge
    files:
      - config/config.yaml
    name: configs
