namespace: consul-ns
namePrefix: consul-

commonLabels:
  environment: production
commonAnnotations:
  note: Hello, I am production!

bases:
  - ../../bases
  - resources

# lets make it simple
# patches:
#   - path: patches/health-sidecar.yaml
#     target:
#       kind: Deployment
#       labelSelector: app.kubernetes.io/component=microservice
#   - path: patches/resource_limit.yaml
#     target:
#       kind: Deployment
#       labelSelector: app.kubernetes.io/component=microservice
#   - path: patches/image-pull-policy-if-not-present.yaml
#     target:
#       kind: Deployment
#       labelSelector: app.kubernetes.io/component=microservice

configMapGenerator:
  # - name: env-vars
  - name: env-vars-common
    behavior: merge
    literals:
      - APP_ENV=production
      - MICRO_REGISTRY=consul
      - MICRO_REGISTRY_ADDRESS="$(CONSUL_SERVICE_NAME):8500"
      - MICRO_REGISTER_TTL="10"
      - MICRO_REGISTER_INTERVAL="5"

secretGenerator:
  - name: secrets
    behavior: replace
    literals:
      - DATABASE_PASSWORD=prod-real-pass

replicas:
  - name: srv
    count: 5

images:
  - name: progrium/consul
    newTag: latest

vars:
  - name: CONSUL_SERVICE_NAME
    objref:
      kind: Service
      name: consul
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
