apiVersion: v1
kind: Service
metadata:
  name: srv
spec:
  type: LoadBalancer
  # We want the servers to become available even if they're not ready
  publishNotReadyAddresses: true
  ports:
    - name: grpc-proxy
      port: 8888
      protocol: TCP
      targetPort: grpc-proxy
