environment: production
name: greetersrv
version: v0.1.0
log:
  level: info
  runtime: prod
  services:
  accountsrv:
    endpoint: accountsrv
    version: v0.1.0
  greetersrv:
    endpoint: greetersrv
    version: v0.1.0
  emailersrv:
    endpoint: emailersrv
    version: v0.1.0
  recordersrv:
    endpoint: recordersrv
    version: v0.1.0

# Feature Flags (enabled/disabled)
features:
  metrics:
    address: prometheus:8125
    flushInterval: 1000000000
    enabled: false
  tracing:
    address: jaeger:6831
    flushInterval: 5000000000
    enabled: false
  mtls:
    certfile: certs/micro.crt
    keyfile: certs/micro.key
    cafile: certs/ca.crt
    servername: "*"
    enabled: false
  validator:
    enabled: true
  reqlogs:
    enabled: true
  translogs:
    topic: recordersrv
    enabled: true
