apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: emailer
  name: emailer
spec:
  selector:
    matchLabels:
      app: emailer
  template:
    metadata:
      labels:
        app: emailer
      name: emailer
    spec:
      serviceAccountName: micro
      containers:
        - name: emailer
          image: xmlking/emailer-srv:latest
          imagePullPolicy: Always
          ports:
            - name: grpc
              containerPort: 8080
              protocol: TCP
            - name: broker
              containerPort: 10001
              protocol: TCP
          env:
            - name: MICRO_REGISTRY
              value: consul
            - name: MICRO_REGISTRY_ADDRESS
              value: "consul:8500"
            - name: MICRO_SERVER_ADDRESS
              value: 0.0.0.0:8080
            - name: MICRO_BROKER_ADDRESS
              value: 0.0.0.0:10001
            - name: MICRO_LOG_LEVEL
              value: debug
            - name: APP_ENV
              value: production
            - name: CONFIG_DIR
              value: /config
            - name: CONFIG_FILE
              value: config.yaml
