commonLabels:
  app.kubernetes.io/name: consul
  app.kubernetes.io/instance: consul-abcxzy
  app.kubernetes.io/component: infra
  app.kubernetes.io/part-of: micro-starter-kit
  app.kubernetes.io/managed-by: kustomize

resources:
  - consul.yaml
  - consul-svc.yaml
