apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  strategy:
  type: RollingUpdate
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      name: gateway
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: microhq/micro:kubernetes
          imagePullPolicy: Always
          args:
            - "api"
            - "--handler=rpc"
            - "--address=0.0.0.0:8080"
          env:
            - name: MICRO_SERVER_NAME
              value: gateway
            - name: MICRO_SERVER_ADDRESS
              value: 0.0.0.0:8989
          ports:
            - name: gateway-http
              containerPort: 8080
              protocol: TCP
        - name: health
          command:
            [
              "/health",
              "--health_address=0.0.0.0:8081",
              "--server_name=gateway",
              "--server_address=0.0.0.0:8989",
            ]
          image: microhq/health:kubernetes
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 3
            periodSeconds: 3
