apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-srv
  labels:
    app: account-srv
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: account-srv
  template:
    metadata:
      name: account-srv
      labels:
        app: account-srv
    spec:
      serviceAccountName: micro
      containers:
        - name: account-srv
          # This is the import path for the Go binary to build and run.
          image: github.com/xmlking/micro-starter-kit/srv/account
          imagePullPolicy: Always
          resources:
            limits:
              memory: 2G
            requests:
              memory: 1G
          ports:
            - name: grpc
              containerPort: 8080
              protocol: TCP
          # envFrom:
          #   - secretRef:
          #       name: account-srv
          #   - configMapRef:
          #       name: account-srv
          # https://github.com/inigofu/temac-user-service/blob/master/deployments/deployment.yml
          env:
            - name: MICRO_REGISTRY
              value: kubernetes
            - name: MICRO_SERVER_ADDRESS
              value: 0.0.0.0:8080
            - name: MICRO_BROKER_ADDRESS
              value: 0.0.0.0:10001
            - name: APP_ENV
              value: production
            - name: CONFIG_DIR
              value: /var/run/ko
            - name: CONFIG_FILE
              value: config.yaml
            # - name: DATABASE_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: account-postgresql
            #       key: postgresql-password
        # - name: health
        #   command: [
        #         "/health",
        #         "--health_address=0.0.0.0:8081",
        #         "--server_name=account-srv",
        #         "--server_address=0.0.0.0:8080"
        #   ]
        #   image: microhq/health:kubernetes
        #   livenessProbe:
        #     httpGet:
        #       path: /health
        #       port: 8081
        #     initialDelaySeconds: 3
        #     periodSeconds: 3
