apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: $(NS)
namePrefix: prod-
nameSuffix: -v1

commonLabels:
  environment: production
  app.kubernetes.io/version: v1
commonAnnotations:
  note: Hello, I am production!

bases:
  - ../../bases
  - ../../bases/consul
  # - ../../bases/gateway
  # - ../../bases/postgres

# enable mage-pull-policy and resource_limit as needed
patches:
  - path: patches/health-sidecar.yaml
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/component=microservice
  # - path: patches/resource_limit.yaml
  #   target:
  #     kind: Deployment
  #     labelSelector: app.kubernetes.io/component=microservice
  - path: patches/image-pull-policy-if-not-present.yaml
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/component=microservice

configMapGenerator:
  # - name: env-vars
  - name: env-vars-common
    behavior: merge
    literals:
      - APP_ENV=production
      - MICRO_REGISTRY=consul
      - MICRO_REGISTRY_ADDRESS="$(CONSUL_SERVICE_NAME):8500"
      - MICRO_REGISTER_TTL="10"
      - MICRO_REGISTER_INTERVAL="5"
      - MICRO_LOG_LEVEL=info

secretGenerator:
  - name: secrets
    behavior: replace
    literals:
      - DATABASE_PASSWORD=prod-real-pass
  - name: regcred
    files:
      - secrets/.dockerconfigjson
    type: kubernetes.io/dockerconfigjson

replicas:
  - name: srv
    count: 1

images:
  - name: consul
    newTag: 1.6.1
  - name: postgres
    newTag: 11.5-alpine
  - name: microhq/micro
    newName: docker.pkg.github.com/xmlking/micro-starter-kit/micro
    newTag: $(IMAGE_VERSION)
  - name: xmlking/account-api
    newName: docker.pkg.github.com/xmlking/micro-starter-kit/account-api
    newTag: $(IMAGE_VERSION)
  - name: xmlking/account-srv
    newName: docker.pkg.github.com/xmlking/micro-starter-kit/account-srv
    newTag: $(IMAGE_VERSION)
  - name: xmlking/emailer-srv
    newName: docker.pkg.github.com/xmlking/micro-starter-kit/emailer-srv
    newTag: $(IMAGE_VERSION)
  - name: xmlking/greeter-srv
    newName: docker.pkg.github.com/xmlking/micro-starter-kit/greeter-srv
    newTag: $(IMAGE_VERSION)
