environment: development
name: accountsrv
version: v0.1.0
log:
  level: debug
  format: text
database:
  dialect: sqlite3
  host: 0.0.0.0
  port: 9999
  Username: sumo
  Password: demo
  database: "file:foobar?mode=memory&cache=shared"
  maxOpenConns: 1
  maxIdleConns: 1
  connMaxLifetime: 1hr
  logging: true
observability:
  metrics:
    address: prometheus:8125
    flushInterval: 1000000000
  tracing:
    address: jaeger:6831
    flushInterval: 5000000000
email:
  username: yourGmailUsername
  password: yourGmailAppPassword
  emailServer: smtp.gmail.com
  port: 587
  from: xmlking@gmail.com

accountsrv:
  endpoint: accountsrv
  version: v0.1.0
greetersrv:
  endpoint: greetersrv
  version: v0.1.0
emailersrv:
  endpoint: emailersrv
  version: v0.1.0


