apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: $(NS)

commonLabels:
  environment: integration
  app.kubernetes.io/version: v1
commonAnnotations:
  note: Hello, I am integration!

bases:
  - ../../bases

# enable mage-pull-policy and resource_limit as needed
patches:
  - path: patches/image-pull-policy-if-not-present.yaml
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/component=microservice

configMapGenerator:
  # - name: env-vars
  - name: env-vars-common
    behavior: merge
    literals:
      - APP_ENV=production
      - MICRO_LOG_LEVEL=debug
      # profile specific variables
      - MICRO_SELECTOR=static
      - MICRO_REGISTRY=memory
      - MICRO_REGISTER_TTL="1200"
      - MICRO_REGISTER_INTERVAL="600"
      - ACCOUNT-SRV_ENDPOINT=$(ACCOUNT-SRV_ENDPOINT)
      - GREETER-SRV_ENDPOINT=$(GREETER-SRV_ENDPOINT)
      - EMAILER-SRV_ENDPOINT=$(EMAILER-SRV_ENDPOINT)
      - ACCOUNT-API_ENDPOINT=$(ACCOUNT-API_ENDPOINT)
      - GATEWAY-SRV_ENDPOINT=$(GATEWAY-SRV_ENDPOINT)

secretGenerator:
  - name: secrets
    behavior: replace
    literals:
      - DATABASE_PASSWORD=e2e-real-pass
  - name: regcred
    files:
      - secrets/.dockerconfigjson
    type: kubernetes.io/dockerconfigjson

replicas:
  - name: srv
    count: 1

images:
  - name: consul
    newTag: 1.6.1
  - name: postgres
    newTag: 11.5-alpine
  - name: microhq/micro
    newName: docker.pkg.github.com/xmlking/micro-starter-kit/micro
    newTag: $(IMAGE_VERSION)
  - name: xmlking/account-api
    newName: docker.pkg.github.com/xmlking/micro-starter-kit/account-api
    newTag: $(IMAGE_VERSION)
  - name: xmlking/account-srv
    newName: docker.pkg.github.com/xmlking/micro-starter-kit/account-srv
    newTag: $(IMAGE_VERSION)
  - name: xmlking/emailer-srv
    newName: docker.pkg.github.com/xmlking/micro-starter-kit/emailer-srv
    newTag: $(IMAGE_VERSION)
  - name: xmlking/greeter-srv
    newName: docker.pkg.github.com/xmlking/micro-starter-kit/greeter-srv
    newTag: $(IMAGE_VERSION)
