commonLabels:
  app.kubernetes.io/name: recorder-srv
  app.kubernetes.io/instance: recorder-srv-abcxzy
  app.kubernetes.io/component: microservice

namePrefix: recorder

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: config
    files:
      - config/config.yaml
  - name: env-vars
    literals:
      - MICRO_SERVER_NAME=recordersrv
      # - MICRO_SERVER_ADVERTISE="$(RECORDER_SRV_ENDPOINT):8080"

vars:
  - name: RECORDER_SRV_ENDPOINT
    objref:
      kind: Service
      name: srv
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
