commonLabels:
  app.kubernetes.io/name: account-api
  app.kubernetes.io/instance: account-api-abcxzy
  app.kubernetes.io/component: microservice

namePrefix: account-api-

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: config
    files:
      - config/config.yaml
  - name: env-vars
    literals:
      - SERVICE_NAME=$(ACCOUNT_API_SERVICE_NAME)
      - MICRO_SERVER_NAME=account-api
      - ACCOUNT_HOST=$(ACCOUNT_SERVICE_NAME)

vars:
  - name: ACCOUNT_API_SERVICE_NAME
    objref:
      kind: Service
      name: srv
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
