commonLabels:
  app.kubernetes.io/name: account-api
  app.kubernetes.io/instance: account-api-abcxzy
  app.kubernetes.io/component: microservice

namePrefix: account-api-

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: config
    files:
      - config/config.yaml
  - name: env-vars
    literals:
      - MICRO_SERVER_NAME=account-api
      # - MICRO_SERVER_ADVERTISE="$(ACCOUNT-API_ENDPOINT):8080"

vars:
  - name: ACCOUNT-API_ENDPOINT
    objref:
      kind: Service
      name: srv
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
