apiVersion: apps/v1
kind: Deployment
metadata:
  name: srv
spec:
  template:
    spec:
      containers:
        - name: srv
          image: microhq/micro:latest
          imagePullPolicy: Always
          args:
            - "api"
            - "--handler=rpc"
            - "--enable_rpc=true"
            - "--address=0.0.0.0:8090"
          ports:
            - name: http-gateway
              containerPort: 8090
              protocol: TCP
          envFrom:
            - configMapRef:
                name: env-vars
            - configMapRef:
                name: env-vars-common
          env:
            - name: MICRO_API_ADDRESS
              value: 0.0.0.0:8090
