apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 8080
      protocol: TCP
      targetPort: gateway-http
  selector:
    app: gateway
