apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: account-srv
  name: account-srv
spec:
  selector:
    matchLabels:
      app: account-srv
  template:
    metadata:
      labels:
        app: account-srv
      name: account-srv
    spec:
      serviceAccountName: micro
      containers:
        - name: account-srv
          image: xmlking/account-srv:0.0.3-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - name: grpc
              containerPort: 8080
              protocol: TCP
          env:
            - name: MICRO_REGISTRY
              value: kubernetes
            - name: MICRO_SERVER_ADDRESS
              value: 0.0.0.0:8080
            - name: MICRO_BROKER_ADDRESS
              value: 0.0.0.0:10001
            - name: MICRO_SELECTOR
              value: static
            - name: MICRO_LOG_LEVEL
              value: debug
            - name: APP_ENV
              value: production
            - name: CONFIG_DIR
              value: /config
            - name: CONFIG_FILE
              value: config.yaml
