apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gateway
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
      name: gateway
    spec:
      serviceAccountName: micro
      containers:
        - name: gateway
          # image: microhq/micro:kubernetes
          image: xmlking/micro:kubernetes
          imagePullPolicy: Always
          args:
            # web or proxy
            - api
          ports:
            - name: rest
              containerPort: 8080
              protocol: TCP
          env:
            - name: MICRO_REGISTRY
              value: kubernetes
            - name: MICRO_SELECTOR
              value: static
            - name: MICRO_SERVER_NAME
              value: gateway
            - name: MICRO_API_ENABLE_RPC
              value: "true"
            - name: MICRO_LOG_LEVEL
              value: debug
            - name: CORS_ALLOWED_HEADERS
              value: "Authorization,Content-Type"
            - name: CORS_ALLOWED_ORIGINS
              value: "https://api.kashmora.com"
            - name: CORS_ALLOWED_METHODS
              value: "POST,GET"
