apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: greeter
  name: greeter
spec:
  selector:
    matchLabels:
      app: greeter
  template:
    metadata:
      labels:
        app: greeter
      name: greeter
    spec:
      serviceAccountName: micro
      containers:
        - name: greeter
          image: xmlking/greeter-srv:latest
          imagePullPolicy: Always
          ports:
            - name: grpc
              containerPort: 8080
              protocol: TCP
            - name: broker
              containerPort: 10001
              protocol: TCP
          env:
            - name: MICRO_REGISTRY
              value: kubernetes
            - name: MICRO_SELECTOR
              value: static
            - name: MICRO_SERVER_NAME
              value: greeter
            - name: MICRO_SERVER_ADDRESS
              value: 0.0.0.0:8080
            - name: MICRO_BROKER_ADDRESS
              value: 0.0.0.0:10001
            - name: MICRO_LOG_LEVEL
              value: debug
            - name: APP_ENV
              value: production
            - name: CONFIG_DIR
              value: /config
            - name: CONFIG_FILE
              value: config.yaml
