commonLabels:
  app.kubernetes.io/name: consul
  app.kubernetes.io/instance: consul-abcxzy
  app.kubernetes.io/component: infra
  app.kubernetes.io/part-of: micro-starter-kit
  app.kubernetes.io/managed-by: kustomize
commonAnnotations:
  org: acmeCorporation

resources:
  - service-account.yaml
  - deployment.yaml
  - service.yaml

vars:
  - name: CONSUL_SERVICE_NAME
    objref:
      kind: Service
      name: consul
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
