commonLabels:
  app.kubernetes.io/name: consul
  app.kubernetes.io/instance: consul-abcxzy
  app.kubernetes.io/component: infra
  app.kubernetes.io/part-of: micro-starter-kit
  app.kubernetes.io/managed-by: kustomize
commonAnnotations:
  org: acmeCorporation

resources:
  # if you want retry-join=k8s, enable deployment-auto.yaml and service-account.yaml,
  # otherwise enable deployment.yaml and service.yaml
  # - deployment-auto.yaml
  # - service-account.yaml
  - deployment.yaml
  - service.yaml
  # optionally expose UI port
  - service-ui.yaml

vars:
  - name: CONSUL_SRV_ENDPOINT
    objref:
      kind: Service
      name: consul
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
