namespace: default
commonLabels:
  app.kubernetes.io/part-of: micro-starter-kit
  app.kubernetes.io/managed-by: kustomize
commonAnnotations:
  org: acmeCorporation

# labels for generated ConfigMap at this level
generatorOptions:
  labels:
    app.kubernetes.io/name: app-config
    app.kubernetes.io/instance: app-config-abcxzy
    app.kubernetes.io/component: config

bases:
  - account-srv
  - account-api
  - emailer-srv
  - postgres
  - gateway

# resources:
#   - micro-service-account.yaml

configMapGenerator:
  - name: env-vars
    literals:
      - MICRO_REGISTRY=kubernetes
      - MICRO_SERVER_ADDRESS=0.0.0.0:8080
      - APP_ENV=development
  - name: configs
    files:
      - config/config.yaml
# secretGenerator:
# - name: secrets
#   env: secrets
# secretGenerator:
# - name: app-tls
#   files:
#     - secret/tls.cert
#     - secret/tls.key

vars:
  - name: GATEWAY_SERVICE_NAME
    objref:
      kind: Service
      name: gateway
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
  - name: ACCOUNT_SERVICE_NAME
    objref:
      kind: Service
      name: account-srv
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
