apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: $(NS)
namePrefix: k8s-
nameSuffix: -v1

commonLabels:
  environment: production
  app.kubernetes.io/version: v1
commonAnnotations:
  note: Hello, I am production!

bases:
  - ../../bases
  # - ../../bases/postgres

resources:
  - resources/micro-service-account.yaml

# enable mage-pull-policy and resource_limit as needed
patches:
  - path: patches/micro-sa.yaml
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/component=microservice
  - path: patches/health-sidecar.yaml
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/component=microservice
  # - path: patches/resource_limit.yaml
  #   target:
  #     kind: Deployment
  #     labelSelector: app.kubernetes.io/component=microservice
  - path: patches/image-pull-policy-if-not-present.yaml
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/component=microservice

configMapGenerator:
  # - name: env-vars
  - name: env-vars-common
    behavior: merge
    literals:
      - APP_ENV=production
      - MICRO_REGISTRY=kubernetes
      - MICRO_LOG_LEVEL=info

secretGenerator:
  - name: secrets
    behavior: replace
    literals:
      - DATABASE_PASSWORD=prod-real-pass

replicas:
  - name: srv
    count: 1

images:
  - name: consul
    newTag: 1.6.1
  - name: postgres
    newTag: 11.5-alpine
  - name: microhq/micro
    newName: docker.pkg.github.com/xmlking/micro-starter-kit/micro
    newTag: $(IMAGE_VERSION)
  - name: xmlking/account-api
    newName: docker.pkg.github.com/xmlking/micro-starter-kit/account-api
    newTag: $(IMAGE_VERSION)
  - name: xmlking/account-srv
    newName: docker.pkg.github.com/xmlking/micro-starter-kit/account-srv
    newTag: $(IMAGE_VERSION)
  - name: xmlking/emailer-srv
    newName: docker.pkg.github.com/xmlking/micro-starter-kit/emailer-srv
    newTag: $(IMAGE_VERSION)
  - name: xmlking/greeter-srv
    newName: docker.pkg.github.com/xmlking/micro-starter-kit/greeter-srv
    newTag: $(IMAGE_VERSION)

vars:
  - name: CONSUL_SA
    objref:
      kind: ServiceAccount
      name: micro
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
