namespace: default
namePrefix: k8s-

commonLabels:
  environment: production
commonAnnotations:
  note: Hello, I am production!

bases:
  - ../../bases

resources:
  - resources/micro-service-account.yaml

# lets make it simple
patches:
  - path: patches/micro-sa.yaml
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/component=microservice
  # - path: patches/health-sidecar.yaml
  #   target:
  #     kind: Deployment
  #     labelSelector: app.kubernetes.io/component=microservice
  # - path: patches/image-pull-policy-if-not-present.yaml
  #   target:
  #     kind: Deployment
  #     labelSelector: app.kubernetes.io/component=microservice

configMapGenerator:
  # - name: env-vars
  - name: env-vars-common
    behavior: merge
    literals:
      - APP_ENV=production
      - MICRO_REGISTRY=kubernetes

secretGenerator:
  - name: secrets
    behavior: replace
    literals:
      - DATABASE_PASSWORD=prod-real-pass

replicas:
  - name: srv
    count: 1

images:
  - name: docker.io/bitnami/postgresql
    newTag: "10.7.0"

vars:
  - name: CONSUL_SA
    objref:
      kind: ServiceAccount
      name: micro
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
