environment: development
name: greeter-srv
version: 0.1.0
log:
  level: debug
  format: text
observability:
  metrics:
    address: localhost:8125
    flushInterval: 1000000000
  tracing:
    address: jaeger:6831
    flushInterval: 5000000000
