apiVersion: v1
kind: Service
metadata:
  name: greeter-srv
  labels:
    app: greeter-srv
spec:
  type: ClusterIP
  ports:
    - name: grpc-port
      port: 8080
      protocol: TCP
      targetPort: grpc-port
  selector:
    app: greeter-srv
