name: Deploy on Release
on:
  release:
    types: [published]
jobs:
  deploy:
    name: Deploy Release Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Check out Release
        run: |
          echo "TODO trigger deployment"
          echo "task - ${{ github.event.release.tag_name }}"
          echo "task - ${{ github.event.release }}"
