name: Deploy on Release
on:
  release:
    types: [published]
jobs:
  deploy:
    name: Deploy Release Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Check out Release
        env:
          RELEASE_TAG: ${{ github.event.release.tag_name }}
          DOWNLOAD_URL: ${{ github.event.release.assets[0].browser_download_url }}
        run: |
          echo "TODO trigger deployment"
          echo "task - ${{ github.event.release.tag_name }}"
          echo "task - ${{ github.event.release.upload_url }}"
          echo "task - ${{ toJson(github.event.release.assets) }}"
          echo "browser_download_urls - ${{ toJson(github.event.release.assets.*.browser_download_url) }}"
          echo "$RELEASE_TAG"
          echo "$DOWNLOAD_URL"
      - name: Script
        uses: actions/github-script@0.2.0
        with:
          debug: true
          github-token: ${{github.token}}
          script: |
            const payload = context.payload
            console.log(context)
            console.log("----")
            console.log(github.event)
