name: Test on Push
on: [push]
jobs:
  build:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Get dependencies
        run: go mod download
      - name: Lint
        run: make lint
      - name: Unit Test
        run: make test
      # - name: Integration Test
      #   run: make inte
      - name: Upload coverage to Codecov
        # -U "--proxy http://http-proxy"
        run: bash <(curl -s https://codecov.io/bash)
          -F unittests
          -n codecov-micros
          -f ./build/coverage.txt
          -B ${{ github.head_ref }}
          -C ${{ github.event.after }}
          -P ${{ github.event.number }}
          -T ${{ GITHUB_REF#refs/tags/ }}
          -Z || echo 'Codecov upload failed'
        # run: bash <(curl -s https://codecov.io/bash) -F unittests -f ./build/coverage.txt -n codecov-umbrella
        env:
          CI: true
          CODECOV_SLUG: ":xmlking/:micro-starter-kit"
          CODECOV_NAME: codecov-micros
          CODECOV_ENV: github-action
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
