name: Test on Push
on: [push]
jobs:
  build:
    name: Lint and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: [1.12]
        os: [ubuntu-latest]
        # go: [1.12, 1.13]
        # os: [ubuntu-latest,  macos-latest]
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Get dependencies
        run: go mod download
        # env:
        #   GO111MODULE: "on"
        #   GOPROXY: https://proxy.golang.org
      - name: Lint
        run: make lint
      - name: Unit Test
        run: make test TARGET=emailer
      # - name: Integration Test
      #   run: make inte
