name: Build on Release
on: [release]
# on:
#   push:
#     branches:
#       - master
#       - 'releases/*'
#     tags:
#     - 'v*'
#   pull_request:
#     branches:
#       - master
jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Get dependencies
        run: go mod download
      - name: Lint
        run: make lint
      - name: Unit Test
        run: make test
      - name: Integration Test
        run: make inte
      # - name: Build
      #   run: go build -v ./cmd/gophrase.go
      #   env:
      #     CGO_ENABLED: 0
      # - name: Build Cross Platform Binaries
      #   run: |
      #     make build_binaries
      #     find binaries -type f | xargs ls -ltrh
      #     cat binaries/sha256sum.txt
      #     ./$(find binaries -name "*.linux.amd64")
      #     ./$(find binaries -name "*.linux.amd64") -n 6
      #     ./$(find binaries -name "*.linux.amd64") --help || true
      # - name: docker-publish
      #   uses: docker://docker
      #   env:
      #     DOCKER_USERNAME: ${{ secrets.docker_username }}
      #     DOCKER_PASSWORD: ${{ secrets.docker_password }}
      #   with:
      #     entrypoint: sh
      #     args: ci/docker-build.sh
