email:
  username: yourGmailUsername
  password: yourGmailAppPassword
  email_server: smtp.gmail.com
  port: 587
  from: from@gmail.com

services:
  account:
    endpoint: mkit.service.account:8080
    version: v0.1.0
  greeter:
    endpoint: mkit.service.greeter:8080
    version: v0.1.0
  emailer:
    endpoint: mkit.service.emailer:8080
    version: v0.1.0
  recorder:
    endpoint: mkit.service.recorder:8080
    version: v0.1.0

features:
  metrics:
    address: prometheus:8125
    flush_interval: 1000000000
    enabled: false
  tracing:
    address: jaeger:6831
    flush_interval: 5000000000
    enabled: false
  tls:
    cert_file: /config/certs/upstream-localhost-cert.pem
    key_file: /config/certs/upstream-localhost-key.pem
    ca_file: /config/certs/upstream-ca-cert.pem
    servername: "*"
    enabled: false
  validator:
    enabled: true
  reqlogs:
    enabled: true
  translogs:
    topic: mkit.service.recorder
    enabled: true
